services:
  - type: web
    name: rainy-byte
    runtime: node
    startCommand: yarn start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
